"""Increase password_hash lenght to 256

Revision ID: 92664ffb7b1d
Revises: 0067312462ab
Create Date: 2025-08-11 16:30:11.454445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92664ffb7b1d'
down_revision = '0067312462ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
